PikachuPlainFrames:		INCLUDE "gfx/pokemon/pikachu/frames.asm"
PikachuSurfFrames: 		INCLUDE "gfx/pokemon/pikachu_surf/frames.asm"
PikachuFlyFrames:  		INCLUDE "gfx/pokemon/pikachu_fly/frames.asm"
PikachuRBFrames:  		INCLUDE "gfx/pokemon/pikachu_rb/frames.asm"

CharmeleonPlainFrames:		INCLUDE "gfx/pokemon/charmeleon/frames.asm"
CharmeleonRocketFrames:		INCLUDE "gfx/pokemon/charmeleon_rocket/frames.asm"

CharizardPlainFrames:		INCLUDE "gfx/pokemon/charizard/frames.asm"
CharizardRocketFrames:		INCLUDE "gfx/pokemon/charizard_rocket/frames.asm"

WeezingPlainFrames:		INCLUDE "gfx/pokemon/weezing/frames.asm"
WeezingRocketFrames:		INCLUDE "gfx/pokemon/weezing_rocket/frames.asm"

CrobatPlainFrames:		INCLUDE "gfx/pokemon/crobat/frames.asm"
CrobatRocketFrames:		INCLUDE "gfx/pokemon/crobat_rocket/frames.asm"

ArbokPlainFrames:		INCLUDE "gfx/pokemon/arbok/frames.asm"
ArbokRocketFrames:		INCLUDE "gfx/pokemon/arbok_rocket/frames.asm"

GolbatPlainFrames:		INCLUDE "gfx/pokemon/golbat/frames.asm"
GolbatRocketFrames:		INCLUDE "gfx/pokemon/golbat_rocket/frames.asm"

SnorlaxPlainFrames:		INCLUDE "gfx/pokemon/snorlax/frames.asm"
SnorlaxApricornFrames:		INCLUDE "gfx/pokemon/snorlax_apricorn/frames.asm"

ShucklePlainFrames:         	INCLUDE "gfx/pokemon/shuckle/frames.asm"
ShuckleShuckieNeutralFrames:	INCLUDE "gfx/pokemon/shuckle/frames.asm"
ShuckleShuckieHappyFrames:  	INCLUDE "gfx/pokemon/shuckle_shuckie_happy/frames.asm"

UnownAFrames:			INCLUDE "gfx/pokemon/unown_a/frames.asm"
UnownBFrames:			INCLUDE "gfx/pokemon/unown_b/frames.asm"
UnownCFrames:			INCLUDE "gfx/pokemon/unown_c/frames.asm"
UnownDFrames:			INCLUDE "gfx/pokemon/unown_d/frames.asm"
UnownEFrames:			INCLUDE "gfx/pokemon/unown_e/frames.asm"
UnownFFrames:			INCLUDE "gfx/pokemon/unown_f/frames.asm"
UnownGFrames:			INCLUDE "gfx/pokemon/unown_g/frames.asm"
UnownHFrames:			INCLUDE "gfx/pokemon/unown_h/frames.asm"
UnownIFrames:			INCLUDE "gfx/pokemon/unown_i/frames.asm"
UnownJFrames:			INCLUDE "gfx/pokemon/unown_j/frames.asm"
UnownKFrames:			INCLUDE "gfx/pokemon/unown_k/frames.asm"
UnownLFrames:			INCLUDE "gfx/pokemon/unown_l/frames.asm"
UnownMFrames:			INCLUDE "gfx/pokemon/unown_m/frames.asm"
UnownNFrames:			INCLUDE "gfx/pokemon/unown_n/frames.asm"
UnownOFrames:			INCLUDE "gfx/pokemon/unown_o/frames.asm"
UnownPFrames:			INCLUDE "gfx/pokemon/unown_p/frames.asm"
UnownQFrames:			INCLUDE "gfx/pokemon/unown_q/frames.asm"
UnownRFrames:			INCLUDE "gfx/pokemon/unown_r/frames.asm"
UnownSFrames:			INCLUDE "gfx/pokemon/unown_s/frames.asm"
UnownTFrames:			INCLUDE "gfx/pokemon/unown_t/frames.asm"
UnownUFrames:			INCLUDE "gfx/pokemon/unown_u/frames.asm"
UnownVFrames:			INCLUDE "gfx/pokemon/unown_v/frames.asm"
UnownWFrames:			INCLUDE "gfx/pokemon/unown_w/frames.asm"
UnownXFrames:			INCLUDE "gfx/pokemon/unown_x/frames.asm"
UnownYFrames:			INCLUDE "gfx/pokemon/unown_y/frames.asm"
UnownZFrames:			INCLUDE "gfx/pokemon/unown_z/frames.asm"

MagikarpPlainFrames:		INCLUDE "gfx/pokemon/magikarp/frames.asm"
MagikarpXSFrames:		INCLUDE "gfx/pokemon/magikarp_xs/frames.asm"
MagikarpXLFrames:		INCLUDE "gfx/pokemon/magikarp_xl/frames.asm"