PikachuPlainAnimationIdle:		INCLUDE "gfx/pokemon/pikachu/anim_idle.asm"
PikachuSurfAnimationIdle: 		INCLUDE "gfx/pokemon/pikachu_surf/anim_idle.asm"
PikachuFlyAnimationIdle:  		INCLUDE "gfx/pokemon/pikachu_fly/anim_idle.asm"

ShucklePlainAnimationIdle: 		INCLUDE "gfx/pokemon/shuckle/anim_idle.asm"
ShuckleShuckieNeutralAnimationIdle: 	INCLUDE "gfx/pokemon/shuckle/anim_idle.asm"
ShuckleShuckieHappyAnimationIdle: 	INCLUDE "gfx/pokemon/shuckle_shuckie_happy/anim_idle.asm"

UnownAAnimationIdle:			INCLUDE "gfx/pokemon/unown_a/anim_idle.asm"
UnownBAnimationIdle:			INCLUDE "gfx/pokemon/unown_b/anim_idle.asm"
UnownCAnimationIdle:			INCLUDE "gfx/pokemon/unown_c/anim_idle.asm"
UnownDAnimationIdle:			INCLUDE "gfx/pokemon/unown_d/anim_idle.asm"
UnownEAnimationIdle:			INCLUDE "gfx/pokemon/unown_e/anim_idle.asm"
UnownFAnimationIdle:			INCLUDE "gfx/pokemon/unown_f/anim_idle.asm"
UnownGAnimationIdle:			INCLUDE "gfx/pokemon/unown_g/anim_idle.asm"
UnownHAnimationIdle:			INCLUDE "gfx/pokemon/unown_h/anim_idle.asm"
UnownIAnimationIdle:			INCLUDE "gfx/pokemon/unown_i/anim_idle.asm"
UnownJAnimationIdle:			INCLUDE "gfx/pokemon/unown_j/anim_idle.asm"
UnownKAnimationIdle:			INCLUDE "gfx/pokemon/unown_k/anim_idle.asm"
UnownLAnimationIdle:			INCLUDE "gfx/pokemon/unown_l/anim_idle.asm"
UnownMAnimationIdle:			INCLUDE "gfx/pokemon/unown_m/anim_idle.asm"
UnownNAnimationIdle:			INCLUDE "gfx/pokemon/unown_n/anim_idle.asm"
UnownOAnimationIdle:			INCLUDE "gfx/pokemon/unown_o/anim_idle.asm"
UnownPAnimationIdle:			INCLUDE "gfx/pokemon/unown_p/anim_idle.asm"
UnownQAnimationIdle:			INCLUDE "gfx/pokemon/unown_q/anim_idle.asm"
UnownRAnimationIdle:			INCLUDE "gfx/pokemon/unown_r/anim_idle.asm"
UnownSAnimationIdle:			INCLUDE "gfx/pokemon/unown_s/anim_idle.asm"
UnownTAnimationIdle:			INCLUDE "gfx/pokemon/unown_t/anim_idle.asm"
UnownUAnimationIdle:			INCLUDE "gfx/pokemon/unown_u/anim_idle.asm"
UnownVAnimationIdle:			INCLUDE "gfx/pokemon/unown_v/anim_idle.asm"
UnownWAnimationIdle:			INCLUDE "gfx/pokemon/unown_w/anim_idle.asm"
UnownXAnimationIdle:			INCLUDE "gfx/pokemon/unown_x/anim_idle.asm"
UnownYAnimationIdle:			INCLUDE "gfx/pokemon/unown_y/anim_idle.asm"
UnownZAnimationIdle:			INCLUDE "gfx/pokemon/unown_z/anim_idle.asm"

MagikarpPlainAnimationIdle:		INCLUDE "gfx/pokemon/magikarp/anim_idle.asm"
MagikarpXSAnimationIdle:		INCLUDE "gfx/pokemon/magikarp_xs/anim_idle.asm"
MagikarpXLAnimationIdle:		INCLUDE "gfx/pokemon/magikarp_xl/anim_idle.asm"
